import { Request, Response } from "express";
import prisma from "../lib/prisma.js";
import { z } from "zod";

const createGoalLogSchema = z.object({
  timestamp: z.string().optional(),
  existsOnServer: z.boolean().optional(),
  task: z.object({
    id: z.string(),
    title: z.string(),
    tags: z.array(z.string()),
    priority: z.string(),
    estimatedHours: z.number()
  }),
  table: z.object({
    id: z.string(),
    name: z.string()
  }),
  payload: z.record(z.any())
});

const createTimetableSlotSchema = z.object({
  timestamp: z.string().optional(),
  slot: z.object({
    id: z.string(),
    timeSlot: z.string(),
    activity: z.string(),
    category: z.string()
  })
});

export const getGoalTemplates = async (req: Request, res: Response) => {
  try {
    const uid = req.user?.uid;
    if (!uid) {
      return res.status(401).json({ error: "Unauthorized" });
    }

    const templates = await prisma.goalTemplate.findMany({
      where: { uid, isActive: true },
      orderBy: { createdAt: "desc" }
    });

    res.status(200).json(templates);
  } catch (error) {
    console.error("Error fetching goal templates:", error);
    res.status(500).json({ error: "Internal server error" });
  }
};

export const createGoalLog = async (req: Request, res: Response) => {
  try {
    const uid = req.user?.uid;
    if (!uid) {
      return res.status(401).json({ error: "Unauthorized" });
    }

    const parsedData = createGoalLogSchema.parse(req.body);

    const goalLog = await prisma.goalLog.create({
      data: {
        uid,
        taskId: parsedData.task.id,
        taskTitle: parsedData.task.title,
        tags: parsedData.task.tags,
        priority: parsedData.task.priority,
        estimatedHours: parsedData.task.estimatedHours,
        templateId: parsedData.table.id,
        templateName: parsedData.table.name,
        payload: parsedData.payload,
      }
    });

    res.status(201).json({ success: true, data: goalLog });
  } catch (error) {
    if (error instanceof z.ZodError) {
      return res.status(400).json({ error: "Invalid data", details: error.errors });
    }
    console.error("Error creating goal log:", error);
    res.status(500).json({ error: "Internal server error" });
  }
};

export const createTimetableSlot = async (req: Request, res: Response) => {
  try {
    const uid = req.user?.uid;
    if (!uid) {
      return res.status(401).json({ error: "Unauthorized" });
    }

    const parsedData = createTimetableSlotSchema.parse(req.body);

    const slot = await prisma.timetableSlot.create({
      data: {
        id: parsedData.slot.id, // Keep the same ID generated by the frontend if preferred
        uid,
        timeSlot: parsedData.slot.timeSlot,
        activity: parsedData.slot.activity,
        category: parsedData.slot.category,
      }
    });

    res.status(201).json({ success: true, data: slot });
  } catch (error) {
    if (error instanceof z.ZodError) {
      return res.status(400).json({ error: "Invalid data", details: error.errors });
    }
    console.error("Error creating timetable slot:", error);
    res.status(500).json({ error: "Internal server error" });
  }
};
