swagger: "2.0"
info:
  title: auth-api
  version: 1.0.0
  description: Authentication API Gateway

schemes:
  - https

consumes:
  - application/json

produces:
  - application/json

paths:
  /auth/signup/start:
    post:
      operationId: signupStart

      x-google-backend:
        address: CLOUD_RUN_URL
        path_translation: APPEND_PATH_TO_ADDRESS

      responses:
        "200":
          description: Signup OTP initiated

        "400":
          description: Invalid request

        "429":
          description: Too many requests

        "500":
          description: Internal server error

  /auth/signup/verify:
    post:
      operationId: signupVerify

      x-google-backend:
        address: CLOUD_RUN_URL
        path_translation: APPEND_PATH_TO_ADDRESS

      responses:
        "200":
          description: Signup verification success

        "400":
          description: Invalid verification code

        "401":
          description: Unauthorized

        "429":
          description: Too many requests

        "500":
          description: Internal server error
