name: Terraform

on:
  pull_request:
    paths:
      - "infra/**"

  push:
    branches:
      - main
    paths:
      - "infra/**"

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  TF_ROOT: infra/environments/dev

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.TF_ROOT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.TERRAFORM_SERVICE_ACCOUNT }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve